// Code generated by hertz generator.

package image

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _pictureMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _insertMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _searchMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _searchbyimageMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _searchbytextMw() []app.HandlerFunc {
	// your code...
	return nil
}
